In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
from sklearn.cluster import KMeans
import random

%matplotlib inline

In [ ]:
df = pd.read_csv('/content/OnlineRetail.csv', encoding='cp1252', header =0)
df.head()

InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

      InvoiceDate  UnitPrice  CustomerID         Country  
0  12/1/2010 8:26       2.55     17850.0  United Kingdom  
1  12/1/2010 8:26       3.39     17850.0  United Kingdom  
2  12/1/2010 8:26       2.75     17850.0  United Kingdom  
3  12/1/2010 8:26       3.39     17850.0  United Kingdom  
4  12/1/2010 8:26       3.39     17850.0  United Kingdom

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   InvoiceNo    541909 non-null  object 
 1   StockCode    541909 non-null  object 
 2   Description  540455 non-null  object 
 3   Quantity     541909 non-null  int64  
 4   InvoiceDate  541909 non-null  object 
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object 
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB


In [ ]:
df = df[df['CustomerID'].notnull()]
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   InvoiceNo    406829 non-null  object 
 1   StockCode    406829 non-null  object 
 2   Description  406829 non-null  object 
 3   Quantity     406829 non-null  int64  
 4   InvoiceDate  406829 non-null  object 
 5   UnitPrice    406829 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      406829 non-null  object 
dtypes: float64(2), int64(1), object(5)
memory usage: 27.9+ MB


In [ ]:
df['CustomerID'] = df['CustomerID'].astype(str)
df['InvoiceDate'] = df['InvoiceDate'].astype('datetime64[ns]')
df.head()

InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

          InvoiceDate  UnitPrice CustomerID         Country  
0 2010-12-01 08:26:00       2.55    17850.0  United Kingdom  
1 2010-12-01 08:26:00       3.39    17850.0  United Kingdom  
2 2010-12-01 08:26:00       2.75    17850.0  United Kingdom  
3 2010-12-01 08:26:00       3.39    17850.0  United Kingdom  
4 2010-12-01 08:26:00       3.39    17850.0  United Kingdom

In [ ]:
df = df[df['CustomerID'].notnull()]
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype         
---  ------       --------------   -----         
 0   InvoiceNo    406829 non-null  object        
 1   StockCode    406829 non-null  object        
 2   Description  406829 non-null  object        
 3   Quantity     406829 non-null  int64         
 4   InvoiceDate  406829 non-null  datetime64[ns]
 5   UnitPrice    406829 non-null  float64       
 6   CustomerID   406829 non-null  object        
 7   Country      406829 non-null  object        
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 27.9+ MB


In [ ]:
df['InvoiceDay'] = df['InvoiceDate'].apply(lambda x: dt.datetime(x.year, x.month, x.day))

In [ ]:
df.head()

InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

          InvoiceDate  UnitPrice CustomerID         Country InvoiceDay  
0 2010-12-01 08:26:00       2.55    17850.0  United Kingdom 2010-12-01  
1 2010-12-01 08:26:00       3.39    17850.0  United Kingdom 2010-12-01  
2 2010-12-01 08:26:00       2.75    17850.0  United Kingdom 2010-12-01  
3 2010-12-01 08:26:00       3.39    17850.0  United Kingdom 2010-12-01  
4 2010-12-01 08:26:00       3.39    17850.0  United Kingdom 2010-12-01

In [ ]:
dt.timedelta(1)

datetime.timedelta(days=1)

In [ ]:
pin_date = max(df['InvoiceDay']) + dt.timedelta(1)
pin_date

Timestamp('2011-12-10 00:00:00')

In [ ]:
df['TotalSum'] = df['Quantity'] * df['UnitPrice']
df.head()

InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

          InvoiceDate  UnitPrice CustomerID         Country InvoiceDay  \
0 2010-12-01 08:26:00       2.55    17850.0  United Kingdom 2010-12-01   
1 2010-12-01 08:26:00       3.39    17850.0  United Kingdom 2010-12-01   
2 2010-12-01 08:26:00       2.75    17850.0  United Kingdom 2010-12-01   
3 2010-12-01 08:26:00       3.39    17850.0  United Kingdom 2010-12-01   
4 2010-12-01 08:26:00       3.39    17850.0  United Kingdom 2010-12-01   

   TotalSum  
0     15.30  
1     20.34  
2     22.00  
3     20.34  
4     20.34

In [ ]:
rfm = df.groupby('CustomerID').agg({
    'InvoiceDay': lambda x: (pin_date - x.max()).days,
    'InvoiceNo': 'count',
    'TotalSum': 'sum'
})
rfm

InvoiceDay  InvoiceNo  TotalSum
CustomerID                                 
12346.0            326          2      0.00
12347.0              3        182   4310.00
12348.0             76         31   1797.24
12349.0             19         73   1757.55
12350.0            311         17    334.40
...                ...        ...       ...
18280.0            278         10    180.60
18281.0            181          7     80.82
18282.0              8         13    176.60
18283.0              4        756   2094.88
18287.0             43         70   1837.28

[4372 rows x 3 columns]

In [ ]:
rfm.rename(columns= {
    'InvoiceDay': 'Recency',
    'InvoiceNo': 'Frequency',
    'TotalSum': 'Monetary'
}, inplace=True)
rfm

Recency  Frequency  Monetary
CustomerID                              
12346.0         326          2      0.00
12347.0           3        182   4310.00
12348.0          76         31   1797.24
12349.0          19         73   1757.55
12350.0         311         17    334.40
...             ...        ...       ...
18280.0         278         10    180.60
18281.0         181          7     80.82
18282.0           8         13    176.60
18283.0           4        756   2094.88
18287.0          43         70   1837.28

[4372 rows x 3 columns]

In [ ]:
r_labels = range(4, 0, -1) #[4, 3, 2, 1]
r_groups = pd.qcut(rfm['Recency'], q=4, labels=r_labels)
f_labels = range(1, 5) # [1, 2, 3, 4]
f_groups = pd.qcut(rfm['Frequency'], q=4, labels=f_labels)
m_labels = range(1, 5)
m_groups = pd.qcut(rfm['Monetary'], q=4, labels=m_labels)

In [ ]:
rfm['R'] = r_groups.values
rfm['F'] = f_groups.values
rfm['M'] = m_groups.values
rfm
rfm.to_csv('rfm.csv')

In [ ]:
!sudo apt update
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q http://archive.apache.org/dist/spark/spark-3.1.1/spark-3.1.1-bin-hadoop3.2.tgz
!tar xf spark-3.1.1-bin-hadoop3.2.tgz
!pip install -q findspark
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.1.1-bin-hadoop3.2"
!ls

Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Get:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Get:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [1,192 kB]
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:8 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [8,531 kB]
Get:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:10 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [2,454 kB]
Hit:11 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:13 http://archive.ubuntu

In [ ]:
import findspark
findspark.init()

In [ ]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[*]").appName("Cluster Analysis using Kmeans").getOrCreate()
spark

In [ ]:
df = spark.read.csv("/content/rfm.csv", header=True, inferSchema=True)
df.show()

+----------+-------+---------+--------+---+---+---+
|CustomerID|Recency|Frequency|Monetary|  R|  F|  M|
+----------+-------+---------+--------+---+---+---+
|   12346.0|    326|        2|     0.0|  1|  1|  1|
|   12347.0|      3|      182|  4310.0|  4|  4|  4|
|   12348.0|     76|       31| 1797.24|  2|  2|  4|
|   12349.0|     19|       73| 1757.55|  3|  3|  4|
|   12350.0|    311|       17|   334.4|  1|  1|  2|
|   12352.0|     37|       95| 1545.41|  3|  3|  3|
|   12353.0|    205|        4|    89.0|  1|  1|  1|
|   12354.0|    233|       58|  1079.4|  1|  3|  3|
|   12355.0|    215|       13|   459.4|  1|  1|  2|
|   12356.0|     23|       59| 2811.43|  3|  3|  4|
|   12357.0|     34|      131| 6207.67|  3|  4|  4|
|   12358.0|      2|       19| 1168.06|  4|  2|  3|
|   12359.0|      8|      254| 6245.53|  4|  4|  4|
|   12360.0|     53|      129| 2662.06|  2|  4|  4|
|   12361.0|    288|       10|   189.9|  1|  1|  1|
|   12362.0|      4|      274| 5154.58|  4|  4|  4|
|   12363.0|

In [ ]:
from pyspark.ml.feature import VectorAssembler, StandardScaler
from pyspark.ml.clustering import KMeans
from pyspark.ml.evaluation import ClusteringEvaluator


assembler = VectorAssembler(inputCols=df.columns, outputCol="features")
assembled_df = assembler.transform(df)

scaler = StandardScaler(inputCol="features", outputCol="scaledFeatures", withStd=True, withMean=False)
scaler_model = scaler.fit(assembled_df)
scaled_df = scaler_model.transform(assembled_df)

In [ ]:
kmeans = KMeans(k=10, maxIter=300, seed=42, featuresCol="scaledFeatures", predictionCol="prediction")
model = kmeans.fit(scaled_df)

In [ ]:
predictions = model.transform(scaled_df)
predictions = predictions.withColumnRenamed("prediction", "kmeans_cluster")
result_df = predictions.select(*df.columns, "kmeans_cluster")
result_df.show()

+----------+-------+---------+--------+---+---+---+--------------+
|CustomerID|Recency|Frequency|Monetary|  R|  F|  M|kmeans_cluster|
+----------+-------+---------+--------+---+---+---+--------------+
|   12346.0|    326|        2|     0.0|  1|  1|  1|             5|
|   12347.0|      3|      182|  4310.0|  4|  4|  4|             3|
|   12348.0|     76|       31| 1797.24|  2|  2|  4|             0|
|   12349.0|     19|       73| 1757.55|  3|  3|  4|             0|
|   12350.0|    311|       17|   334.4|  1|  1|  2|             5|
|   12352.0|     37|       95| 1545.41|  3|  3|  3|             0|
|   12353.0|    205|        4|    89.0|  1|  1|  1|             5|
|   12354.0|    233|       58|  1079.4|  1|  3|  3|             5|
|   12355.0|    215|       13|   459.4|  1|  1|  2|             5|
|   12356.0|     23|       59| 2811.43|  3|  3|  4|             0|
|   12357.0|     34|      131| 6207.67|  3|  4|  4|             3|
|   12358.0|      2|       19| 1168.06|  4|  2|  3|           

In [ ]:
evaluator = ClusteringEvaluator(featuresCol="features", predictionCol="prediction", metricName="silhouette")
silhouette = evaluator.evaluate(predictions)
print(f"Silhouette Score: {silhouette}")

Silhouette Score: 0.9578162376053938


In [ ]:
centers = model.clusterCenters()
print("Cluster Centers:")
for center in centers:
    print(center)

Cluster Centers:
[  95.13971631   75.77966903 1125.84145957]
[1.50000000e+00 1.25900000e+03 2.67963755e+05]
[6.64285714e+00 1.64142857e+03 5.55973379e+04]
[   17.8852459    428.94262295 13658.21163934]
[1.15000000e+01 2.11300000e+03 1.39291095e+05]
